apiVersion: v1
kind: ServiceAccount
metadata:
  name: sekstant

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sekstant
rules:
- apiGroups: [""]
  resources: ["services", "pods"]
  verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sekstant
roleRef:
  kind: ClusterRole
  name: sekstant
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  namespace: default
  name: sekstant

---

apiVersion: v1
kind: Pod
metadata:
  name: sekstant
spec:
  serviceAccountName: sekstant
  containers:
  - name: sekstant
    image: gcr.io/sekstant/dev
    ports:
    - containerPort: 11456
    env:
    - name: GRAPHIQL
      value: "enabled"
